name: dart_image_grabber
description: Download image from a web page
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  http: ^0.13.6
  html: ^0.15.4
  path: ^1.8.3
  args: ^2.4.2

